# Generated by Django 4.2.5 on 2023-09-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CubeSat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
