# Generated by Django 4.2.5 on 2023-09-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CubeSat', '0002_person_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
