# Generated by Django 4.2.5 on 2023-09-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CubeSat', '0003_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
