# Generated by Django 4.2.5 on 2023-09-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CubeSat', '0005_customer_detail_employer_request_requeststodetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='position',
            field=models.CharField(choices=[('Junior manager', 'Junior Manager'), ('Senior manager', 'Senior Manager')], default='Junior manager', max_length=30),
        ),
    ]
