# Generated by Django 4.2.5 on 2023-09-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CubeSat', '0007_request_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.IntegerField()),
                ('max_current_of_solar_panel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('category_of_product', models.CharField(choices=[('Power Modules', 'Power Modules'), ('Structures', 'Structures'), ('Solar Panels', 'Solar Panels')], max_length=30)),
                ('id_in_category', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='requeststodetails',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CubeSat.product'),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
