# Generated by Django 4.2.5 on 2023-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CubeSat', '0008_powermodules_product_alter_requeststodetails_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Sales',
        ),
        migrations.RemoveField(
            model_name='powermodules',
            name='max_current_of_solar_panel',
        ),
        migrations.AddField(
            model_name='powermodules',
            name='max_current_of_solar_panel_in_channel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powermodules',
            name='max_power_consumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powermodules',
            name='max_total_current_of_solar_panel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='powermodules',
            name='voltage',
            field=models.IntegerField(default=0),
        ),
    ]
