# Generated by Django 4.2.5 on 2023-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CubeSat', '0009_rename_request_sales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('type_of_element', models.CharField()),
                ('open_circuit_voltage', models.DecimalField(decimal_places=2, max_digits=16)),
                ('short_circuit_current', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=16)),
                ('length', models.DecimalField(decimal_places=2, max_digits=16)),
                ('width', models.DecimalField(decimal_places=2, max_digits=16)),
                ('height', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_of_push_springs', models.IntegerField()),
                ('min_operating_temperature', models.DecimalField(decimal_places=2, max_digits=16)),
                ('max_operating_temperature', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.RenameModel(
            old_name='RequestsToDetails',
            new_name='SalesToProducts',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='powermodules',
            name='name',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='powermodules',
            name='max_current_of_solar_panel_in_channel',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='powermodules',
            name='max_power_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='powermodules',
            name='max_total_current_of_solar_panel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='powermodules',
            name='voltage',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
