# Generated by Django 4.2.5 on 2023-09-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CubeSat', '0010_solarpanels_structures_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={},
        ),
    ]
