# Generated by Django 4.2.5 on 2023-09-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CubeSat', '0011_alter_customer_options_alter_employer_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Orders',
        ),
        migrations.RenameModel(
            old_name='SalesToProducts',
            new_name='OrdersToProducts',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='powermodules',
            options={'verbose_name_plural': 'Блоки питания'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Детали'},
        ),
        migrations.AlterModelOptions(
            name='solarpanels',
            options={'verbose_name_plural': 'Солнечные панели'},
        ),
        migrations.AlterModelOptions(
            name='structures',
            options={'verbose_name_plural': 'Корпусы'},
        ),
    ]
