# Generated by Django 4.2.8 on 2024-02-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='delivery_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
